local p = require('claret.palette').dark
local pl = require('claret.palette').light

local function write_if_changed(path, content)
  local existing = ''
  if vim.fn.filereadable(path) == 1 then
    existing = table.concat(vim.fn.readfile(path), '\n')
  end

  if existing == content then
    return false
  end

  vim.fn.mkdir(vim.fn.fnamemodify(path, ':h'), 'p')
  vim.fn.writefile(vim.split(content, '\n', { plain = true }), path)
  return true
end

-- Convert a "#RRGGBB" hex into "R G B" zellij/kdl triple.
local function hex_rgb(hex)
  local r = tonumber(hex:sub(2, 3), 16)
  local g = tonumber(hex:sub(4, 5), 16)
  local b = tonumber(hex:sub(6, 7), 16)
  return string.format('%d %d %d', r, g, b)
end

local generated = {}

-- ---------------------------------------------------------------------------
-- ghostty
-- ---------------------------------------------------------------------------
generated['ports/ghostty/claret-dark.conf'] = table.concat({
  '# AUTO-GENERATED by scripts/generate_ports.lua. Do not edit manually.',
  'background = ' .. p.bg,
  'foreground = ' .. p.text,
  'cursor-color = ' .. p.gold_1,
  'selection-background = ' .. p.bg_mute,
  'selection-foreground = ' .. p.text,
  '',
  'palette = 0=' .. p.divider,
  'palette = 1=' .. p.terra_1,
  'palette = 2=' .. p.sage_1,
  'palette = 3=' .. p.gold_1,
  'palette = 4=' .. p.slate_1,
  'palette = 5=' .. p.rose_1,
  'palette = 6=' .. p.sage_2,
  'palette = 7=' .. p.text_2,
  'palette = 8=' .. p.text_4,
  'palette = 9=' .. p.terra_2,
  'palette = 10=' .. p.sage_1,
  'palette = 11=' .. p.gold_2,
  'palette = 12=' .. p.slate_1,
  'palette = 13=' .. p.rose_2,
  'palette = 14=' .. p.sage_2,
  'palette = 15=' .. p.text,
}, '\n')

-- ---------------------------------------------------------------------------
-- opencode (full slot coverage, dark + light paired)
-- Diff highlight backgrounds use tinted bg mixes rather than saturated
-- foreground colors so inline highlights remain readable.
-- Shape per https://opencode.ai/theme.json; uses `defs` palette refs.
-- ---------------------------------------------------------------------------
local function oc_pair(dark, light)
  return '{ "dark": "' .. dark .. '", "light": "' .. light .. '" }'
end
generated['ports/opencode/claret.json'] = table.concat({
  '{',
  '  "$schema": "https://opencode.ai/theme.json",',
  '  "defs": {',
  '    "dBg": "' .. p.bg .. '",',
  '    "dBgSoft": "' .. p.bg_soft .. '",',
  '    "dBgMute": "' .. p.bg_mute .. '",',
  '    "dDivider": "' .. p.divider .. '",',
  '    "dText": "' .. p.text .. '",',
  '    "dText3": "' .. p.text_3 .. '",',
  '    "dText4": "' .. p.text_4 .. '",',
  '    "dRose1": "' .. p.rose_1 .. '",',
  '    "dRose2": "' .. p.rose_2 .. '",',
  '    "dGold1": "' .. p.gold_1 .. '",',
  '    "dGold2": "' .. p.gold_2 .. '",',
  '    "dSage1": "' .. p.sage_1 .. '",',
  '    "dSage2": "' .. p.sage_2 .. '",',
  '    "dSlate1": "' .. p.slate_1 .. '",',
  '    "dSlate2": "' .. p.slate_2 .. '",',
  '    "dTerra1": "' .. p.terra_1 .. '",',
  '    "dDiffAddBg": "#1D2418",',
  '    "dDiffRemBg": "#2A1417",',
  '    "lBg": "' .. pl.bg .. '",',
  '    "lBgSoft": "' .. pl.bg_soft .. '",',
  '    "lBgMute": "' .. pl.bg_mute .. '",',
  '    "lDivider": "' .. pl.divider .. '",',
  '    "lText": "' .. pl.text .. '",',
  '    "lText3": "' .. pl.text_3 .. '",',
  '    "lText4": "' .. pl.text_4 .. '",',
  '    "lRose1": "' .. pl.rose_1 .. '",',
  '    "lRose2": "' .. pl.rose_2 .. '",',
  '    "lGold1": "' .. pl.gold_1 .. '",',
  '    "lGold2": "' .. pl.gold_2 .. '",',
  '    "lSage1": "' .. pl.sage_1 .. '",',
  '    "lSage2": "' .. pl.sage_2 .. '",',
  '    "lSlate1": "' .. pl.slate_1 .. '",',
  '    "lSlate2": "' .. pl.slate_2 .. '",',
  '    "lTerra1": "' .. pl.terra_1 .. '",',
  '    "lDiffAddBg": "#EAF1E2",',
  '    "lDiffRemBg": "#F5E3E1"',
  '  },',
  '  "theme": {',
  '    "primary": ' .. oc_pair('dRose1', 'lRose1') .. ',',
  '    "secondary": ' .. oc_pair('dSlate1', 'lSlate1') .. ',',
  '    "accent": ' .. oc_pair('dGold1', 'lGold1') .. ',',
  '    "error": ' .. oc_pair('dTerra1', 'lTerra1') .. ',',
  '    "warning": ' .. oc_pair('dGold1', 'lGold1') .. ',',
  '    "success": ' .. oc_pair('dSage1', 'lSage1') .. ',',
  '    "info": ' .. oc_pair('dSlate1', 'lSlate1') .. ',',
  '    "text": ' .. oc_pair('dText', 'lText') .. ',',
  '    "textMuted": ' .. oc_pair('dText3', 'lText3') .. ',',
  '    "background": ' .. oc_pair('dBg', 'lBg') .. ',',
  '    "backgroundPanel": ' .. oc_pair('dBgSoft', 'lBgSoft') .. ',',
  '    "backgroundElement": ' .. oc_pair('dBgMute', 'lBgMute') .. ',',
  '    "border": ' .. oc_pair('dDivider', 'lDivider') .. ',',
  '    "borderActive": ' .. oc_pair('dRose1', 'lRose1') .. ',',
  '    "borderSubtle": ' .. oc_pair('dDivider', 'lDivider') .. ',',
  '    "diffAdded": ' .. oc_pair('dSage1', 'lSage1') .. ',',
  '    "diffRemoved": ' .. oc_pair('dTerra1', 'lTerra1') .. ',',
  '    "diffContext": ' .. oc_pair('dBgSoft', 'lBgSoft') .. ',',
  '    "diffHunkHeader": ' .. oc_pair('dBgMute', 'lBgMute') .. ',',
  '    "diffHighlightAdded": ' .. oc_pair('dDiffAddBg', 'lDiffAddBg') .. ',',
  '    "diffHighlightRemoved": ' .. oc_pair('dDiffRemBg', 'lDiffRemBg') .. ',',
  '    "diffAddedBg": ' .. oc_pair('dDiffAddBg', 'lDiffAddBg') .. ',',
  '    "diffRemovedBg": ' .. oc_pair('dDiffRemBg', 'lDiffRemBg') .. ',',
  '    "diffContextBg": ' .. oc_pair('dBgSoft', 'lBgSoft') .. ',',
  '    "diffLineNumber": ' .. oc_pair('dText3', 'lText3') .. ',',
  '    "diffAddedLineNumberBg": ' .. oc_pair('dDiffAddBg', 'lDiffAddBg') .. ',',
  '    "diffRemovedLineNumberBg": ' .. oc_pair('dDiffRemBg', 'lDiffRemBg') .. ',',
  '    "markdownText": ' .. oc_pair('dText', 'lText') .. ',',
  '    "markdownHeading": ' .. oc_pair('dRose1', 'lRose1') .. ',',
  '    "markdownLink": ' .. oc_pair('dSlate1', 'lSlate1') .. ',',
  '    "markdownLinkText": ' .. oc_pair('dSlate1', 'lSlate1') .. ',',
  '    "markdownCode": ' .. oc_pair('dSage1', 'lSage1') .. ',',
  '    "markdownBlockQuote": ' .. oc_pair('dText3', 'lText3') .. ',',
  '    "markdownEmph": ' .. oc_pair('dGold1', 'lGold1') .. ',',
  '    "markdownStrong": ' .. oc_pair('dRose1', 'lRose1') .. ',',
  '    "markdownHorizontalRule": ' .. oc_pair('dText3', 'lText3') .. ',',
  '    "markdownListItem": ' .. oc_pair('dText', 'lText') .. ',',
  '    "markdownListEnumeration": ' .. oc_pair('dText3', 'lText3') .. ',',
  '    "markdownImage": ' .. oc_pair('dSlate1', 'lSlate1') .. ',',
  '    "markdownImageText": ' .. oc_pair('dSlate1', 'lSlate1') .. ',',
  '    "markdownCodeBlock": ' .. oc_pair('dSage1', 'lSage1') .. ',',
  '    "syntaxComment": ' .. oc_pair('dText4', 'lText4') .. ',',
  '    "syntaxKeyword": ' .. oc_pair('dRose1', 'lRose1') .. ',',
  '    "syntaxFunction": ' .. oc_pair('dGold1', 'lGold1') .. ',',
  '    "syntaxVariable": ' .. oc_pair('dText', 'lText') .. ',',
  '    "syntaxString": ' .. oc_pair('dSage1', 'lSage1') .. ',',
  '    "syntaxNumber": ' .. oc_pair('dGold1', 'lGold1') .. ',',
  '    "syntaxType": ' .. oc_pair('dSlate1', 'lSlate1') .. ',',
  '    "syntaxOperator": ' .. oc_pair('dText3', 'lText3') .. ',',
  '    "syntaxPunctuation": ' .. oc_pair('dText3', 'lText3') .. '',
  '  }',
  '}',
}, '\n')

-- ---------------------------------------------------------------------------
-- yazi (newer theme format)
-- Filetype rules extended for orphan/exec/directory fallbacks and
-- document/archive mime coverage.
-- ---------------------------------------------------------------------------
generated['ports/yazi/claret-dark.yazi/flavor.toml'] = table.concat({
  '# AUTO-GENERATED by scripts/generate_ports.lua. Do not edit manually.',
  '[manager]',
  'cwd = { fg = "' .. p.gold_1 .. '" }',
  'hovered = { fg = "' .. p.text .. '", bg = "' .. p.bg_mute .. '" }',
  'preview_hovered = { fg = "' .. p.text .. '", bg = "' .. p.bg_mute .. '" }',
  'find_keyword = { fg = "' .. p.bg .. '", bg = "' .. p.gold_1 .. '", bold = true }',
  'find_position = { fg = "' .. p.slate_1 .. '", bold = true }',
  'marker_copied = { fg = "' .. p.sage_1 .. '", bg = "' .. p.sage_1 .. '" }',
  'marker_cut = { fg = "' .. p.terra_1 .. '", bg = "' .. p.terra_1 .. '" }',
  'marker_marked = { fg = "' .. p.rose_1 .. '", bg = "' .. p.rose_1 .. '" }',
  'count_copied = { fg = "' .. p.bg .. '", bg = "' .. p.sage_1 .. '" }',
  'count_cut = { fg = "' .. p.bg .. '", bg = "' .. p.terra_1 .. '" }',
  'count_selected = { fg = "' .. p.bg .. '", bg = "' .. p.rose_1 .. '" }',
  '',
  '[status]',
  'separator_open = ""',
  'separator_close = ""',
  'separator_style = { fg = "' .. p.divider .. '", bg = "' .. p.bg .. '" }',
  'mode_normal = { fg = "' .. p.bg .. '", bg = "' .. p.gold_1 .. '", bold = true }',
  'mode_select = { fg = "' .. p.bg .. '", bg = "' .. p.rose_1 .. '", bold = true }',
  'mode_unset = { fg = "' .. p.bg .. '", bg = "' .. p.slate_1 .. '", bold = true }',
  'progress_label = { fg = "' .. p.text .. '", bold = true }',
  'progress_normal = { fg = "' .. p.gold_1 .. '", bg = "' .. p.bg_soft .. '" }',
  'progress_error = { fg = "' .. p.terra_1 .. '", bg = "' .. p.bg_soft .. '" }',
  '',
  '[input]',
  'border = { fg = "' .. p.rose_1 .. '" }',
  'title = { fg = "' .. p.text .. '" }',
  'value = { fg = "' .. p.text .. '" }',
  'selected = { fg = "' .. p.bg .. '", bg = "' .. p.gold_1 .. '" }',
  '',
  '[select]',
  'border = { fg = "' .. p.rose_1 .. '" }',
  'active = { fg = "' .. p.gold_1 .. '" }',
  'inactive = { fg = "' .. p.text_3 .. '" }',
  '',
  '[tasks]',
  'border = { fg = "' .. p.rose_1 .. '" }',
  'title = { fg = "' .. p.text .. '" }',
  'hovered = { fg = "' .. p.text .. '", bg = "' .. p.bg_mute .. '" }',
  '',
  '[which]',
  'cols = 3',
  'mask = { bg = "' .. p.bg_soft .. '" }',
  'cand = { fg = "' .. p.slate_1 .. '" }',
  'rest = { fg = "' .. p.text_3 .. '" }',
  'desc = { fg = "' .. p.gold_1 .. '" }',
  'separator = "  "',
  'separator_style = { fg = "' .. p.divider .. '" }',
  '',
  '[help]',
  'on = { fg = "' .. p.sage_1 .. '" }',
  'run = { fg = "' .. p.rose_1 .. '" }',
  'hovered = { bg = "' .. p.bg_mute .. '" }',
  'footer = { fg = "' .. p.text .. '", bg = "' .. p.bg_soft .. '" }',
  '',
  '[notify]',
  'title_info = { fg = "' .. p.slate_1 .. '" }',
  'title_warn = { fg = "' .. p.gold_1 .. '" }',
  'title_error = { fg = "' .. p.terra_1 .. '" }',
  '',
  '[filetype]',
  'rules = [',
  '  { mime = "image/*", fg = "' .. p.rose_1 .. '" },',
  '  { mime = "video/*", fg = "' .. p.rose_2 .. '" },',
  '  { mime = "audio/*", fg = "' .. p.sage_1 .. '" },',
  '  { mime = "application/{zip,rar,7z*,tar,gzip,xz,zstd,bzip*,lzma,compress,archive,cpio,arj,xar,ms-cab*}", fg = "'
    .. p.gold_2
    .. '" },',
  '  { mime = "application/{pdf,doc,rtf,vnd.*}", fg = "' .. p.rose_2 .. '" },',
  '  { mime = "application/json", fg = "' .. p.slate_1 .. '" },',
  '  { mime = "application/toml", fg = "' .. p.slate_1 .. '" },',
  '  { name = "*", is = "orphan", fg = "' .. p.terra_1 .. '" },',
  '  { name = "*", is = "exec", fg = "' .. p.sage_1 .. '" },',
  '  { name = "*/", fg = "' .. p.gold_1 .. '" },',
  '  { name = "*", fg = "' .. p.text .. '" }',
  ']',
}, '\n')

-- ---------------------------------------------------------------------------
-- bat (full syntax + markup + diff scope coverage)
-- ---------------------------------------------------------------------------
local function bat_scope(name, scope, fg, font_style)
  local lines = {
    '    <dict>',
    '      <key>name</key>',
    '      <string>' .. name .. '</string>',
    '      <key>scope</key>',
    '      <string>' .. scope .. '</string>',
    '      <key>settings</key>',
    '      <dict>',
  }
  if fg then
    table.insert(lines, '        <key>foreground</key>')
    table.insert(lines, '        <string>' .. fg .. '</string>')
  end
  if font_style then
    table.insert(lines, '        <key>fontStyle</key>')
    table.insert(lines, '        <string>' .. font_style .. '</string>')
  end
  table.insert(lines, '      </dict>')
  table.insert(lines, '    </dict>')
  table.insert(lines, '')
  return table.concat(lines, '\n')
end

local bat_lines = {
  '<?xml version="1.0" encoding="UTF-8"?>',
  '<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">',
  '<plist version="1.0">',
  '<dict>',
  '  <key>name</key>',
  '  <string>ClaretDark</string>',
  '  <key>settings</key>',
  '  <array>',
  '    <dict>',
  '      <key>settings</key>',
  '      <dict>',
  '        <key>background</key>',
  '        <string>' .. p.bg .. '</string>',
  '        <key>foreground</key>',
  '        <string>' .. p.text .. '</string>',
  '        <key>caret</key>',
  '        <string>' .. p.text .. '</string>',
  '        <key>selection</key>',
  '        <string>' .. p.bg_mute .. '</string>',
  '        <key>lineHighlight</key>',
  '        <string>' .. p.bg_mute .. '</string>',
  '        <key>gutterForeground</key>',
  '        <string>' .. p.text_4 .. '</string>',
  '      </dict>',
  '    </dict>',
  '',
}

local bat_scopes = {
  { 'Comment', 'comment, punctuation.definition.comment', p.text_4, 'italic' },
  { 'Keyword', 'keyword, storage.type, storage.modifier', p.rose_1 },
  { 'Function', 'entity.name.function, support.function', p.gold_1 },
  { 'String', 'string, punctuation.definition.string', p.sage_1 },
  { 'Number', 'constant.numeric', p.gold_1 },
  { 'Constant', 'constant, constant.language, variable.language', p.gold_1 },
  { 'Type', 'entity.name.type, entity.name.class, support.type, support.class', p.slate_1 },
  { 'Variable', 'variable, variable.parameter', p.text },
  { 'Parameter', 'variable.parameter', p.text, 'italic' },
  { 'Property', 'variable.other.property, variable.other.member', p.rose_2 },
  {
    'JSON/YAML/TOML Keys',
    'meta.mapping.key string, support.type.property-name.json, punctuation.support.type.property-name.json, support.type.property-name.toml, punctuation.support.type.property-name.toml, entity.name.tag.yaml, support.type.property-name.yaml',
    p.rose_2,
  },
  { 'Operator', 'keyword.operator', p.text_3 },
  { 'Punctuation', 'punctuation', p.text_3 },
  { 'Decorator', 'meta.decorator, punctuation.decorator', p.gold_1, 'italic' },
  { 'Tag', 'entity.name.tag', p.slate_1 },
  { 'Tag Attribute', 'entity.other.attribute-name', p.slate_2 },
  { 'Invalid', 'invalid, invalid.illegal', p.terra_1 },
  { 'Escape', 'constant.character.escape', p.slate_1 },
  { 'Markup Heading', 'markup.heading', p.rose_1, 'bold' },
  { 'Markup Bold', 'markup.bold', nil, 'bold' },
  { 'Markup Italic', 'markup.italic', nil, 'italic' },
  { 'Markup Link', 'markup.underline.link, string.other.link', p.slate_1 },
  { 'Diff Added', 'markup.inserted', p.sage_1 },
  { 'Diff Deleted', 'markup.deleted', p.terra_1 },
  { 'Diff Changed', 'markup.changed', p.gold_1 },
}
for _, s in ipairs(bat_scopes) do
  table.insert(bat_lines, bat_scope(s[1], s[2], s[3], s[4]))
end

-- bat_scope already appends a trailing blank line; close the plist.
table.insert(bat_lines, '  </array>')
table.insert(bat_lines, '  <key>uuid</key>')
table.insert(bat_lines, '  <string>claret-nvim-bat-theme</string>')
table.insert(bat_lines, '</dict>')
table.insert(bat_lines, '</plist>')

local bat_content = table.concat(bat_lines, '\n')
generated['ports/bat/ClaretDark.tmTheme'] = bat_content

-- yazi flavor bundles the same tmTheme for syntax preview highlighting
generated['ports/yazi/claret-dark.yazi/tmtheme.xml'] = bat_content

-- ---------------------------------------------------------------------------
-- zellij (UI-component spec, not palette form)
-- Frames are gold on focus, rose on mode switch, so the "green" slot stays
-- available for success semantics elsewhere in plugins.
-- ---------------------------------------------------------------------------
local function zl_block(name, base, bg, e0, e1, e2, e3)
  return {
    '    ' .. name .. ' {',
    '      base ' .. base,
    '      background ' .. bg,
    '      emphasis_0 ' .. e0,
    '      emphasis_1 ' .. e1,
    '      emphasis_2 ' .. e2,
    '      emphasis_3 ' .. e3,
    '    }',
  }
end

local zl = {
  '// AUTO-GENERATED by scripts/generate_ports.lua. Do not edit manually.',
  '// UI-component spec so pane frames can be coloured independently of the',
  '// ANSI green slot. Active pane frames use gold.',
  'themes {',
  '  claret-dark {',
}
local bg_rgb = hex_rgb(p.bg)
local bgm_rgb = hex_rgb(p.bg_mute)
local divider_rgb = hex_rgb(p.divider)
local text_rgb = hex_rgb(p.text)
local text4_rgb = hex_rgb(p.text_4)
local rose1_rgb = hex_rgb(p.rose_1)
local gold1_rgb = hex_rgb(p.gold_1)
local gold2_rgb = hex_rgb(p.gold_2)
local sage1_rgb = hex_rgb(p.sage_1)
local type1_rgb = hex_rgb(p.slate_1)
local terra1_rgb = hex_rgb(p.terra_1)

local function extend(dst, src)
  for _, v in ipairs(src) do
    table.insert(dst, v)
  end
end

extend(
  zl,
  zl_block('text_unselected', text_rgb, bg_rgb, gold1_rgb, type1_rgb, sage1_rgb, rose1_rgb)
)
extend(zl, zl_block('text_selected', text_rgb, bgm_rgb, gold1_rgb, type1_rgb, sage1_rgb, rose1_rgb))
extend(
  zl,
  zl_block('ribbon_selected', bg_rgb, rose1_rgb, gold1_rgb, text_rgb, sage1_rgb, type1_rgb)
)
extend(
  zl,
  zl_block('ribbon_unselected', bg_rgb, text_rgb, rose1_rgb, type1_rgb, sage1_rgb, gold1_rgb)
)
extend(zl, zl_block('table_title', gold1_rgb, '0', rose1_rgb, type1_rgb, sage1_rgb, text_rgb))
extend(
  zl,
  zl_block('table_cell_selected', text_rgb, bgm_rgb, gold1_rgb, type1_rgb, sage1_rgb, rose1_rgb)
)
extend(
  zl,
  zl_block('table_cell_unselected', text_rgb, bg_rgb, gold1_rgb, type1_rgb, sage1_rgb, rose1_rgb)
)
extend(zl, zl_block('list_selected', text_rgb, bgm_rgb, gold1_rgb, type1_rgb, sage1_rgb, rose1_rgb))
extend(
  zl,
  zl_block('list_unselected', text_rgb, bg_rgb, gold1_rgb, type1_rgb, sage1_rgb, rose1_rgb)
)
extend(
  zl,
  zl_block('frame_unselected', divider_rgb, '0', text4_rgb, divider_rgb, divider_rgb, divider_rgb)
)
extend(zl, zl_block('frame_selected', gold1_rgb, '0', gold2_rgb, text_rgb, rose1_rgb, '0'))
extend(zl, zl_block('frame_highlight', rose1_rgb, '0', gold1_rgb, rose1_rgb, rose1_rgb, rose1_rgb))
extend(zl, zl_block('exit_code_success', sage1_rgb, '0', type1_rgb, bg_rgb, gold1_rgb, rose1_rgb))
extend(zl, zl_block('exit_code_error', terra1_rgb, '0', gold1_rgb, '0', '0', '0'))

-- multiplayer_user_colors uses flat `player_N R G B` lines rather than blocks.
table.insert(zl, '    multiplayer_user_colors {')
table.insert(zl, '      player_1 ' .. rose1_rgb)
table.insert(zl, '      player_2 ' .. type1_rgb)
table.insert(zl, '      player_3 0')
table.insert(zl, '      player_4 ' .. gold1_rgb)
table.insert(zl, '      player_5 ' .. sage1_rgb)
table.insert(zl, '      player_6 0')
table.insert(zl, '      player_7 ' .. terra1_rgb)
table.insert(zl, '      player_8 0')
table.insert(zl, '      player_9 0')
table.insert(zl, '      player_10 0')
table.insert(zl, '    }')
table.insert(zl, '  }')
table.insert(zl, '}')

generated['ports/zellij/claret-dark.kdl'] = table.concat(zl, '\n')

-- ---------------------------------------------------------------------------
-- kitty
-- ---------------------------------------------------------------------------
generated['ports/kitty/claret.conf'] = table.concat({
  '# AUTO-GENERATED by scripts/generate_ports.lua. Do not edit manually.',
  '# vim:ft=kitty',
  '',
  '## name:     Claret',
  '## author:   cfbender',
  '## license:  MIT',
  '## blurb:    Warm burgundy-gold-sage colorscheme',
  '',
  '# The basic colors',
  'foreground              ' .. p.text,
  'background              ' .. p.bg,
  'selection_foreground    ' .. p.bg,
  'selection_background    ' .. p.rose_1,
  '',
  '# Cursor colors',
  'cursor                  ' .. p.text,
  'cursor_text_color       ' .. p.bg,
  '',
  '# URL underline color when hovering with mouse',
  'url_color               ' .. p.gold_1,
  '',
  '# Kitty window border colors',
  'active_border_color     ' .. p.rose_1,
  'inactive_border_color   ' .. p.divider,
  'bell_border_color       ' .. p.gold_1,
  '',
  '# OS Window titlebar colors',
  'wayland_titlebar_color system',
  'macos_titlebar_color system',
  '',
  '# Tab bar colors',
  'active_tab_foreground   ' .. p.bg,
  'active_tab_background   ' .. p.rose_1,
  'inactive_tab_foreground ' .. p.text_2,
  'inactive_tab_background ' .. p.bg_soft,
  'tab_bar_background      ' .. p.bg,
  '',
  '# Colors for marks (marked text in the terminal)',
  'mark1_foreground ' .. p.bg,
  'mark1_background ' .. p.slate_1,
  'mark2_foreground ' .. p.bg,
  'mark2_background ' .. p.rose_1,
  'mark3_foreground ' .. p.bg,
  'mark3_background ' .. p.gold_1,
  '',
  '# The 16 terminal colors',
  '',
  '# black',
  'color0 ' .. p.divider,
  'color8 ' .. p.text_4,
  '',
  '# red',
  'color1 ' .. p.terra_1,
  'color9 ' .. p.rose_1,
  '',
  '# green',
  'color2  ' .. p.sage_1,
  'color10 ' .. p.sage_1,
  '',
  '# yellow',
  'color3  ' .. p.gold_1,
  'color11 ' .. p.gold_2,
  '',
  '# blue',
  'color4  ' .. p.slate_1,
  'color12 ' .. p.slate_1,
  '',
  '# magenta',
  'color5  ' .. p.rose_2,
  'color13 ' .. p.rose_3,
  '',
  '# cyan',
  'color6  ' .. p.sage_2,
  'color14 ' .. p.sage_2,
  '',
  '# white',
  'color7  ' .. p.text_2,
  'color15 ' .. p.text,
}, '\n')

-- ---------------------------------------------------------------------------
-- starship (palette fragment)
-- Intended to be pasted or included under [palettes.claret] in starship.toml.
-- ---------------------------------------------------------------------------
generated['ports/starship/claret.toml'] = table.concat({
  '# AUTO-GENERATED by scripts/generate_ports.lua. Do not edit manually.',
  '# Palette fragment for starship. Usage:',
  '#   palette = "claret"',
  '#   [palettes.claret]',
  '#   <copy contents below>',
  '',
  '[palettes.claret]',
  'overlay = "' .. p.bg .. '"',
  'fg      = "' .. p.text .. '"',
  'red     = "' .. p.terra_1 .. '"',
  'green   = "' .. p.sage_1 .. '"',
  'blue    = "' .. p.slate_1 .. '"',
  'yellow  = "' .. p.gold_1 .. '"',
  'magenta = "' .. p.rose_2 .. '"',
  'orange  = "' .. p.gold_2 .. '"',
  'cyan    = "' .. p.sage_2 .. '"',
  'black   = "' .. p.bg .. '"',
  'white   = "' .. p.text .. '"',
}, '\n')

-- ---------------------------------------------------------------------------
-- vicinae (browser theme)
-- ---------------------------------------------------------------------------
generated['ports/vicinae/claret-dark.toml'] = table.concat({
  '# AUTO-GENERATED by scripts/generate_ports.lua. Do not edit manually.',
  '',
  '[meta]',
  'name = "Claret Dark"',
  'description = "Dark palette from the Claret Neovim colorscheme"',
  'variant = "dark"',
  'inherits = "vicinae-dark"',
  '',
  '[colors.core]',
  'accent = "' .. p.slate_1 .. '"',
  'accent_foreground = "' .. p.bg .. '"',
  'background = "' .. p.bg .. '"',
  'foreground = "' .. p.text .. '"',
  'secondary_background = "' .. p.bg_soft .. '"',
  'border = "' .. p.divider .. '"',
  '',
  '[colors.main_window]',
  'border = "' .. p.divider .. '"',
  'footer = { background = "colors.core.secondary_background" }',
  '',
  '[colors.settings_window]',
  'border = "' .. p.divider .. '"',
  '',
  '[colors.accents]',
  'blue = "' .. p.slate_1 .. '"',
  'green = "' .. p.sage_1 .. '"',
  'magenta = "' .. p.rose_1 .. '"',
  'orange = "' .. p.gold_2 .. '"',
  'red = "' .. p.terra_1 .. '"',
  'yellow = "' .. p.gold_1 .. '"',
  'cyan = "' .. p.sage_2 .. '"',
  'purple = "' .. p.rose_2 .. '"',
  '',
  '# For now, shortcuts cannot have their own dedicated background',
  '[colors.shortcut]',
  'border = "colors.core.border"',
  '',
  '[colors.text]',
  'default = "colors.core.foreground"',
  'muted = "' .. p.text_3 .. '"',
  'danger = "' .. p.terra_1 .. '"',
  'success = "' .. p.sage_1 .. '"',
  'placeholder = "' .. p.text_4 .. '"',
  'selection = { background = "' .. p.bg_mute .. '", foreground = "' .. p.text .. '" }',
  '',
  '[colors.text.links]',
  'default = "' .. p.slate_1 .. '"',
  'visited = "' .. p.rose_2 .. '"',
  '',
  '[colors.input]',
  'border = "' .. p.divider .. '"',
  'border_focus = "' .. p.slate_1 .. '"',
  'border_error = "' .. p.terra_1 .. '"',
  '',
  '[colors.button.primary]',
  'background = "' .. p.bg_soft .. '"',
  'foreground = "' .. p.text .. '"',
  'hover = { background = "' .. p.bg_mute .. '" }',
  'focus = { outline = "colors.core.accent" }',
  '',
  '[colors.list.item.hover]',
  'foreground = "' .. p.text .. '"',
  'secondary_foreground = "' .. p.text_3 .. '"',
  '',
  '[colors.list.item.selection]',
  'background = "' .. p.bg_soft .. '"',
  'foreground = "' .. p.text .. '"',
  'secondary_background = "' .. p.bg_soft .. '"',
  'secondary_foreground = "' .. p.text_3 .. '"',
  '',
  '[colors.grid.item]',
  'background = "' .. p.bg_soft .. '"',
  'hover = { outline = "' .. p.slate_1 .. '" }',
  'selection = { outline = "' .. p.slate_1 .. '" }',
  '',
  '[colors.scrollbars]',
  'background = "' .. p.divider .. '"',
  '',
  '[colors.loading]',
  'bar = "' .. p.slate_1 .. '"',
  'spinner = "' .. p.slate_1 .. '"',
}, '\n')

local changed = {}
for path, content in pairs(generated) do
  if write_if_changed(path, content) then
    table.insert(changed, path)
  end
end

table.sort(changed)
if #changed == 0 then
  print('ports generator: no changes')
else
  print('ports generator: updated ' .. table.concat(changed, ', '))
end
